In [9]:
import numpy as np

lista2 = [12, "15-12-1996", 13]
lista = [1, 2, 3, 4, 5]

array_1d = np.array(lista)
array_1d2 = np.array(lista2)   

print(type(lista2))
print(type(array_1d2[1]))
print(array_1d2) 

<class 'list'>
<class 'numpy.str_'>
['12' '15-12-1996' '13']


In [ ]:
import pandas as pd
df = pd.DataFrame({
    "Inicio": [12,100], 
    "Fin": [10, 15-12-1222]
})
df2 = pd.DataFrame({'pais':['MX','AR','MX'], 'ventas':[100,200,150]})
sol=np.array(df2["ventas"])
ab =np.array([[2,3],[4,6]])

ab2 =np.array([[1,7],[5,6]])
print(ab)
print(sol)
print(np.mean(sol))
print(np.dot(ab, ab2))


[[2 3]
 [4 6]]
[100 200 150]
150.0
[[17 32]
 [34 64]]


In [17]:
a=np.array([1,2,3,4,5])

c=np.array([1,2,3,4,5])


print(a+c)
print(np.sqrt(a))
print(np.dot(a,c))
print(np.mean(a))

[ 2  4  6  8 10]
[1.         1.41421356 1.73205081 2.         2.23606798]
55
3.0


In [27]:
b=np.array([[6,7],[3,4]])
e=np.array([[9,8],[16,44]])
#print(np.sqrt(b))
#print(b+e)
#print(np.dot(b,e))
print((b+e)/2)
print(np.mean(e))

[[ 7.5  7.5]
 [ 9.5 24. ]]
19.25


In [28]:
f=np.array([1,2,3,4,5,6,7,8,9,10])
df2 = pd.DataFrame({'pais':['MX','AR','MX'], 'ventas':[100,200,150]})
sol=np.array(df2["ventas"])
print(sol[1:2])
print(sol<5)
print(f[::3])


[200]
[False False False]
[ 1  4  7 10]


In [51]:
G = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(G[:,1]) 
print(G<5)
print(G[G<5])  

[2 5 8]
[[ True  True  True]
 [ True False False]
 [False False False]]
[1 2 3 4]


In [68]:
G = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
H = np.array([9,8,7])

L = G+H
print(L)
G[2,2] = 20
print(G)
print(G[G>4])

[[10 10 10]
 [13 13 13]
 [16 16 16]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]]
[ 5  6  7  8 20]


In [70]:
r = np.random.randint(1,10)
Aleatorio=np.array =(r, r)
print(Aleatorio)

TypeError: 'tuple' object is not callable

In [94]:
from numpy import random as rd
#cast = np.rd.default_rng(42)
Nombres = ["Carlos", "Ana", "Claudia"]
datos = {
    "Paises": rd.choice(Nombres, 10),
    "clavos": rd.random(10)
    }
#Aleatorio = pd.DataFrame(datos)
print(datos)
#print(Aleatorio)


{'Paises': array(['Claudia', 'Ana', 'Claudia', 'Claudia', 'Ana', 'Ana', 'Claudia',
       'Claudia', 'Ana', 'Ana'], dtype='<U7'), 'clavos': array([0.44764791, 0.00120544, 0.90417229, 0.23002023, 0.1083354 ,
       0.61723637, 0.36679061, 0.77765524, 0.16727072, 0.7465549 ])}
