In [3]:
import numpy as np

lista = [1, 2, 3, 4, 5]

array_1d = np.array(lista)   

print(type(array_1d))
print(type(array_1d))
print(array_1d) 

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [17]:
a=np.array([1,2,3,4,5])

c=np.array([1,2,3,4,5])


print(a+c)
print(np.sqrt(a))
print(np.dot(a,c))
print(np.mean(a))

[ 2  4  6  8 10]
[1.         1.41421356 1.73205081 2.         2.23606798]
55
3.0


In [27]:
b=np.array([[6,7],[3,4]])
e=np.array([[9,8],[16,44]])
#print(np.sqrt(b))
#print(b+e)
#print(np.dot(b,e))
print((b+e)/2)
print(np.mean(e))

[[ 7.5  7.5]
 [ 9.5 24. ]]
19.25


In [ ]:
f=np.array([1,2,3,4,5,6,7,8,9,10])
print(f[1:4])
print(f[::2])
print(f[::-1])


[2 3 4]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
[ True  True  True  True False False False False False False]


In [51]:
G = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(G[:,1]) 
print(G<5)
print(G[G<5])  

[2 5 8]
[[ True  True  True]
 [ True False False]
 [False False False]]
[1 2 3 4]


In [68]:
G = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
H = np.array([9,8,7])

L = G+H
print(L)
G[2,2] = 20
print(G)
print(G[G>4])

[[10 10 10]
 [13 13 13]
 [16 16 16]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]]
[ 5  6  7  8 20]
